_BattlePetCompletionist.Enums.Goal = {
    COLLECT = "COLLECT",
    COLLECTRARE = "COLLECTRARE",
    COLLECTMAX = "COLLECTMAX",
    COLLECTMAXRARE = "COLLECTMAXRARE",
}
_BattlePetCompletionist.Enums.MapPinFilter = {
    T1ALL = "T1ALL",
    T2MISSING = "T2MISSING",
    T3NOTRARE = "T3NOTRARE",
    T4NONE = "T4NONE",
    T5NOTMAXCOLLECTED = "T5NOTMAXCOLLECTED",
    T6NAMEFILTER = "T6NAMEFILTER",
    T7NOTMAXRARE = "T7NOTMAXRARE",
}
